CONTIKI=../../../..

CFLAGS+= -DPROJECT_CONF_H=\"project-conf.h\" -I ../netcoding -Wno-unused-variable -Wno-unused-function -Wno-unused-but-set-variable -Wno-uninitialized

CONTIKI_WITH_IPV6 = 1
# MODULES_REL += netcoding

include $(CONTIKI)/Makefile.include
