CONTIKI_PROJECT = 2-xor
# MAKE_MAC = MAKE_MAC_TSCH
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
# CFLAGS += -Wno-unused-variable -Wno-unused-function
# MODULES_REL += netcoding
MODULES += os/services/shell
include $(CONTIKI)/Makefile.include
